# Etapa 1: Construir a aplicação React
FROM node:14 as build

WORKDIR /app

# Copiar os arquivos do package.json e package-lock.json (ou yarn.lock)
COPY package*.json ./

# Instalar as dependências
RUN npm install

# Copiar o código fonte do aplicativo
COPY . .

# Construir a aplicação React
RUN npm run build

# Etapa 2: Criar a imagem final
FROM nginx:alpine

# Copiar os arquivos de build da Etapa 1 para o diretório do servidor Nginx
COPY --from=build /app/build /usr/share/nginx/html

# Definir as configurações do servidor Nginx
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
